### ISSUE TITLE
can you update this for "spatie/laravel-permission": "^3.2"

### ISSUE THREAD

**Issue by Arametheus** [ahmedsaoud31/laravel-permission-to-vuejs#1]
so I have the newest laravel-permission but yours is erroring 
Problem 1
    - Can only install one of: spatie/laravel-permission[v2.x-dev, 3.2.0].
    - Can only install one of: spatie/laravel-permission[v2.x-dev, 3.2.0].
    - Can only install one of: spatie/laravel-permission[v2.x-dev, 3.2.0].
    - ahmedsaoud31/laravel-permission-to-vuejs dev-master requires spatie/laravel-permission ^2.0 -> satisfiable by spatie/laravel-permission[v2.x-dev].
    - Installation request for ahmedsaoud31/laravel-permission-to-vuejs dev-master -> satisfiable by ahmedsaoud31/laravel-permission-to-vuejs[dev-master].
    - Installation request for spatie/laravel-permission ^3.2 -> satisfiable by spatie/laravel-permission[3.2.0].

Thank you

**Comment by ahmedsaoud31** [comment]
Try now.
