### ISSUE TITLE
Best practice to set window.Laravel from VueJS

### ISSUE THREAD

**Issue by vanrijs** [ahmedsaoud31/laravel-permission-to-vuejs#11]
Hi!

I was wondering: what is the best wat to set this variable you use when I use Laravel only as backend (API)?
window.Laravel

In your docs its coming from Laravel but I use Laravel only as backend. 
Ive added 'permissions' => $this->jsPermissions() to my User resource to I have this permissions available in my Vue frontend using {{ this.$auth.user }} 

I think I have two options here:
- Im able to set window.Laravel anywhere so I can use your file
- Ill try to create an own version of your file using this $auth contents.

Looking forward to your reply.

Regards,

Raymond

**Comment by ahmedsaoud31** [comment]
Hi Raymond,
See this:
https://github.com/ahmedsaoud31/laravel-permission-to-vuejs/issues/4#issuecomment-860466190
