### ISSUE TITLE
Support Typescript

### ISSUE THREAD

**Issue by Ali7med** [ahmedsaoud31/laravel-permission-to-vuejs#14]
its miss declaration of type in typescript.
![image](https://user-images.githubusercontent.com/10943632/202433188-5868e115-9ae0-4719-95e9-92015775b10b.png)

thanks

**Comment by quacklabs** [comment]
any hope for this?

**Comment by Lea-Reift** [comment]
Still no fix for this?

**Comment by ahmedsaoud31** [comment]
#22
