### ISSUE TITLE
Usage in the <script> tag

### ISSUE THREAD

**Issue by neov-98** [ahmedsaoud31/laravel-permission-to-vuejs#15]
Please add usage examples in the <script setup> and <script> tags.
Perhaps this is obvious, or the check is not used outside the template.
Thanks!

**Comment by flprblr** [comment]
Hi @Vadim-vg, I had the same problem. Solved in a middleware.

app/Http/Middleware/HandleInertiaRequests.php

`<?php

namespace App\Http\Middleware;

use Illuminate\Http\Request;
use Inertia\Middleware;
use Tightenco\Ziggy\Ziggy;
use Illuminate\Support\Facades\Auth;

class HandleInertiaRequests extends Middleware
{
    /**
     * The root template that is loaded on the first page visit.
     *
     * @var string
     */
    protected $rootView = 'app';

    /**
     * Determine the current asset version.
     */
    public function version(Request $request): ?string
    {
        return parent::version($request);
    }

    /**
     * Define the props that are shared by default.
     *
     * @return array<string, mixed>
     */
    public function share(Request $request): array
    {
        return [
            ...parent::share($request),
            'ziggy' => fn () => [
                ...(new Ziggy)->toArray(),
                'location' => $request->url(),
            ],
            'permissions' => function () {
                $permissions = Auth::check() ? Auth::user()->jsPermissions() : [];
                return $permissions;
            },
        ];
    }
}
`

**Comment by ahmedsaoud31** [comment]
Thanks,
Done, Please Update your package and check README for the example.

**Comment by ahmedsaoud31** [comment]
Thanks,
Sorry about too late replay
Done, I update the package and README for the example.
