### ISSUE TITLE
Missing parts in README.md

### ISSUE THREAD

**Issue by AlexanderMtchedlidze** [ahmedsaoud31/laravel-permission-to-vuejs#16]
To set the permission and rules in the correct manner you should implement them in this way:

`window.Laravel = { jsPermissions: JSON.parse(permissionsData.value) };`

window.Larave because it is initially undefined and window.Laravel.jsPermissions will throw an error if you don't use the approach described above.

Second JSON.parse ensures data, that is in the object is covered in quotes like "rules" and "permissions", to have correct object keys, so they can be accessed correctly in packages index.js file.

**Comment by ahmedsaoud31** [comment]
Thanks and sorry for the late reply, this fixed in npm version @3.0.2
