### ISSUE TITLE
Not working with transfer from mix to vite

### ISSUE THREAD

**Issue by xlcrr** [ahmedsaoud31/laravel-permission-to-vuejs#21]
Getting this error using vue 2

```
[plugin:vite:import-analysis] Failed to resolve entry for package "laravel-permission-to-vuejs". The package may have incorrect main/module/exports specified in its package.json.
```

Fails here

```
import LaravelPermissionToVueJS from 'laravel-permission-to-vuejs';

>>> Vue.use(LaravelPermissionToVueJS);

```

**Comment by xlcrr** [comment]
Potential fix here 

https://github.com/ahmedsaoud31/laravel-permission-to-vuejs/pull/22

**Comment by xlcrr** [comment]
If anyone wants to see how I fixed it by importing one js file into my project 

https://github.com/OpenLitterMap/openlittermap-web/pull/648/commits/3ba0b52bec59f260d83ba59d8dc93599f151b602

**Comment by ahmedsaoud31** [comment]
#22
