### ISSUE TITLE
Vue 3 Compatibility

### ISSUE THREAD

**Issue by RobHowdle** [ahmedsaoud31/laravel-permission-to-vuejs#3]
Hello,

I was trying to use this plugin but it seems it is not compatible with Vue 3? I was getting the following error and I couldn't see anywhere that told me it was compatible so I am assuming that may be my problem. Do you have a plans to make this Vue 3 compatible at all?

`Uncaught TypeError: Vue.prototype is undefined
    install http://poddy.test/js/app.js:64452
    use http://poddy.test/js/app.js:9570
    js http://poddy.test/js/app.js:25907
    __webpack_require__ http://poddy.test/js/app.js:113228
    checkDeferredModulesImpl http://poddy.test/js/app.js:113378
    x http://poddy.test/js/app.js:113391
    <anonymous> http://poddy.test/js/app.js:113398
    <anonymous> http://poddy.test/js/app.js:113400
app.js:64452:3
    install http://poddy.test/js/app.js:64452
    use http://poddy.test/js/app.js:9570
    js http://poddy.test/js/app.js:25907
    __webpack_require__ http://poddy.test/js/app.js:113228
    checkDeferredModulesImpl http://poddy.test/js/app.js:113378
    x http://poddy.test/js/app.js:113391
    <anonymous> http://poddy.test/js/app.js:113398
    <anonymous> http://poddy.test/js/app.js:113400`

Above is the error I was receiving.

Thank you
Rob

**Comment by GonzaNav** [comment]
Hi, @RobHowdle i'm new here!! I'm working in a Laravel-Inertia project and had the same problem and resolved it.
So first you need to search into .node_modules folder, the folder with name laravel-permission-to-vuejs and open the index.js file.
Then replace its content with this one:

```
export default {
	install(app, options) {
		function can(value){
			var permissions = window.Laravel.jsPermissions.permissions;
			var _return = false;
			if(!Array.isArray(permissions)){
				return false;
			}
			if(value.includes('|')){
				value.split('|').forEach(function (item) {
					if(permissions.includes(item.trim())){
						_return = true;
					}
				});
			}else if(value.includes('&')){
				_return = true;
				value.split('&').forEach(function (item) {
					if(!permissions.includes(item.trim())){
						_return = false;
					}
				});
			}else{
				_return = permissions.includes(value.trim());
			}
			return _return;
		}
		app.config.globalProperties.$can = can;

        app.provide("can", {can});  
		
		function is(value){
			var roles = window.Laravel.jsPermissions.roles;
			var _return = false;
			if(!Array.isArray(roles)){
				return false;
			}
			if(value.includes('|')){
				value.split('|').forEach(function (item) {
					if(roles.includes(item.trim())){
						_return = true;
					}
				});
			}else if(value.includes('&')){
				_return = true;
				value.split('&').forEach(function (item) {
					if(!roles.includes(item.trim())){
						_return = false;
					}
				});
			}else{
				_return = roles.includes(value.trim());
			}
			return _return;
		}
		app.config.globalProperties.$is = is;

        app.provide("is", {is}); 
	}

}

```

And in your app.js file should have something like this:

```

//your code
import LaravelPermissionToVueJS from 'laravel-permission-to-vuejs';

const el = document.getElementById('app');
const app = createApp({
//your code
})

 app
     //your code
     .use(LaravelPermissionToVueJS)
     .mount(el)
```
Then you use npm install and npm run dev to save changes.

In your vue component use v-if="$is('some role')" or v-if="$can('some permission')".
Maybe your app.js is different so just import LaravelPermissionToVueJS  and use it where you have to. Glad to help!!

**Comment by GonzaNav** [comment]
> Hello,
> 
> I was trying to use this plugin but it seems it is not compatible with Vue 3? I was getting the following error and I couldn't see anywhere that told me it was compatible so I am assuming that may be my problem. Do you have a plans to make this Vue 3 compatible at all?
> 
> `Uncaught TypeError: Vue.prototype is undefined install http://poddy.test/js/app.js:64452 use http://poddy.test/js/app.js:9570 js http://poddy.test/js/app.js:25907 __webpack_require__ http://poddy.test/js/app.js:113228 checkDeferredModulesImpl http://poddy.test/js/app.js:113378 x http://poddy.test/js/app.js:113391 <anonymous> http://poddy.test/js/app.js:113398 <anonymous> http://poddy.test/js/app.js:113400 app.js:64452:3 install http://poddy.test/js/app.js:64452 use http://poddy.test/js/app.js:9570 js http://poddy.test/js/app.js:25907 __webpack_require__ http://poddy.test/js/app.js:113228 checkDeferredModulesImpl http://poddy.test/js/app.js:113378 x http://poddy.test/js/app.js:113391 <anonymous> http://poddy.test/js/app.js:113398 <anonymous> http://poddy.test/js/app.js:113400`
> 
> Above is the error I was receiving.
> 
> Thank you
> Rob

Hi, @RobHowdle i'm new here!! I'm working in a Laravel-Inertia project and had the same problem and resolved it.
So first you need to search into .node_modules folder, the folder with name laravel-permission-to-vuejs and open the index.js file.
Then replace its content with this one:

```
export default {
	install(app, options) {
		function can(value){
			var permissions = window.Laravel.jsPermissions.permissions;
			var _return = false;
			if(!Array.isArray(permissions)){
				return false;
			}
			if(value.includes('|')){
				value.split('|').forEach(function (item) {
					if(permissions.includes(item.trim())){
						_return = true;
					}
				});
			}else if(value.includes('&')){
				_return = true;
				value.split('&').forEach(function (item) {
					if(!permissions.includes(item.trim())){
						_return = false;
					}
				});
			}else{
				_return = permissions.includes(value.trim());
			}
			return _return;
		}
		app.config.globalProperties.$can = can;

        app.provide("can", {can});  
		
		function is(value){
			var roles = window.Laravel.jsPermissions.roles;
			var _return = false;
			if(!Array.isArray(roles)){
				return false;
			}
			if(value.includes('|')){
				value.split('|').forEach(function (item) {
					if(roles.includes(item.trim())){
						_return = true;
					}
				});
			}else if(value.includes('&')){
				_return = true;
				value.split('&').forEach(function (item) {
					if(!roles.includes(item.trim())){
						_return = false;
					}
				});
			}else{
				_return = roles.includes(value.trim());
			}
			return _return;
		}
		app.config.globalProperties.$is = is;

        app.provide("is", {is}); 
	}

}

```

And in your app.js file should have something like this:

```

//your code
import LaravelPermissionToVueJS from 'laravel-permission-to-vuejs';

const el = document.getElementById('app');
const app = createApp({
//your code
})

 app
     //your code
     .use(LaravelPermissionToVueJS)
     .mount(el)
```
Then you use npm install and npm run dev to save changes.

In your vue component use v-if="$is('some role')" or v-if="$can('some permission')".
Maybe your app.js is different so just import LaravelPermissionToVueJS  and use it where you have to. Glad to help!!

**Comment by pette87** [comment]
Hi,

simple to migrate:

make a "permission.js" file in same directory of your app.js

Put following:

```
module.exports = {
    methods: {
        can(value) {
            var permissions = window.Laravel.jsPermissions.permissions;
            var _return = false;
            if (!Array.isArray(permissions)) {
                return false;
            }
            if (value.includes('|')) {
                value.split('|').forEach(function (item) {
                    if (permissions.includes(item.trim())) {
                        _return = true;
                    }
                });
            } else if (value.includes('&')) {
                _return = true;
                value.split('&').forEach(function (item) {
                    if (!permissions.includes(item.trim())) {
                        _return = false;
                    }
                });
            } else {
                _return = permissions.includes(value.trim());
            }
            return _return;
        },
        is(value) {
            var roles = window.Laravel.jsPermissions.roles;
            var _return = false;
            if (!Array.isArray(roles)) {
                return false;
            }
            if (value.includes('|')) {
                value.split('|').forEach(function (item) {
                    if (roles.includes(item.trim())) {
                        _return = true;
                    }
                });
            } else if (value.includes('&')) {
                _return = true;
                value.split('&').forEach(function (item) {
                    if (!roles.includes(item.trim())) {
                        _return = false;
                    }
                });
            } else {
                _return = roles.includes(value.trim());
            }
            return _return;
        }
    }
}
```

And in your app.js

const app = createApp({ ....
...
.mixin(require('./permission'))
...

Now you can use the "if" variants.

**Comment by ahmedsaoud31** [comment]
Now the package moved to support Vue 3
