### ISSUE TITLE
i get Uncaught SyntaxError: Unexpected token '}' error

### ISSUE THREAD

**Issue by ninja71-mn** [ahmedsaoud31/laravel-permission-to-vuejs#7]
Hi i use this package in spa app, vue 3 and laravel 8 and sanctum
but i get this error

Uncaught SyntaxError: Unexpected token '}'

![image](https://user-images.githubusercontent.com/75197797/144565284-82e0eaf5-10a2-4df0-b94e-2233ef22ab74.png)

**Comment by ahmedsaoud31** [comment]
Check that you add
```
use LaravelAndVueJS\Traits\LaravelPermissionToVueJS;

// Spatie package
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use LaravelPermissionToVueJS;
    
    // Spatie package
    use HasRoles;

    // ...
}
```
In your User Model
